### PR TITLE
Updating project

### PR DESCRIPTION
**Pull request by upkarlidder**
The project will be used at a conference. This PR updates the project to use latest TF and fixes breaking code due to this change.

- [x] updating the project python runtime. The old one is no longer available on IBM Cloud
- [x]  update TF version
- [x] fix breaking code with the TF version update
- [x] re-exported the project zip file

Steps to test the PR:
- sign into IBM Cloud
- ensure you have a COS service
- check out the branch
- import the assets/coffee-donut.zip project into Watson Studio
- run through the notebook

Signed-off-by: Upkar Lidder <ulidder@us.ibm.com>

### CODE REVIEW

**Comment by upkarlidder** [comment]
@johnwalicki are you able to try out the branch and review the PR?

@jjasghar is going to run this next week at open source summit.

**Comment by johnwalicki** [comment]
@upkarlidder  - Fantastic - I'll test the steps in the PR.

**Comment by upkarlidder** [comment]
Thanks @johnwalicki. I updated the code in the notebook that fixed some errors with TF version update. The README still might need some screenshot updates.

**Review by johnwalicki — CHANGES_REQUESTED** [review]
New runtime and tensorflow libs work correctly.
The `Coffee Bag 2.jpg` in the zip file should be renamed to `Coffee.jpg` so that the notebook cells work correctly.

**Comment by upkarlidder** [comment]
Added `Coffee.jpg` to the data assets and updated PR. @johnwalicki please review.

image

FYI @trulymobilenwp @jjasghar 

image

**Review by johnwalicki — APPROVED** [review]
Excellent Approved

**Comment by johnwalicki** [comment]
Let's merge this to main.

**Pull request merged**
